zf:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  volumes:
   - .:/var/www
  links:
    - php7_cache
php7_cache:
  image: redis:latest
  ports:
    - "6380:6379"
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
php7_composer:
  image: composer:latest
  command: install --ignore-platform-reqs
  environment:
    - "COMPOSER_AUTH=${COMPOSER_AUTH}"
  volumes:
    - ../var/www