zf:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  volumes:
   - .:/app
  links:
    - php7_cache
    - elasticsearch
php7_cache:
  image: redis:latest
  ports:
    - "6380:6379"
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
php7_composer:
  image: composer:latest
  command: install --ignore-platform-reqs
  environment:
    - "COMPOSER_AUTH=${COMPOSER_AUTH}"
  volumes:
    - .:/app
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
  container_name: elasticsearch
  ports: ['9200:9200']